### ISSUE TITLE
How can I contribute with a new translation?

### ISSUE THREAD

**Issue by anibaldeboni** [MiyooMini/language-pack#1]
Just need to open a pull request?
I'd like to contribute with pt_BR translation.

**Comment by anibaldeboni** [comment]
The commit is already done. Just give-me permissions and I open the PR

**Comment by TriForceX** [comment]
can you try to do the pr? i think you dont need extra permssions

**Comment by anibaldeboni** [comment]
> can you try to do the pr? i think you dont need extra permssions

I tried to publish the branch but it says I don't have permission. If there's a way to open a PR from a forked repo into this, I'd need some help cause I never did it before 😅

**Comment by TriForceX** [comment]
oh sorry, if you already tried and didnt worked maybe ive messed up something on the repo settings.
you have permissions now!
